// <auto-generated />
using System;
using CCDMSServices.ORM.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCDMSServices.Migrations
{
    [DbContext(typeof(CCDMSDbContext))]
    partial class CCDMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CCDMSServices.ORM.Entities.FileData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Count")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Hours")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Mean")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Median")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Std")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("FileData");
                });

            modelBuilder.Entity("CCDMSServices.ORM.Entities.Files", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoopNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("DataCollectionTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GrowthStartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("CCDMSServices.ORM.Entities.FileData", b =>
                {
                    b.HasOne("CCDMSServices.ORM.Entities.Files", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });
#pragma warning restore 612, 618
        }
    }
}
